# Site settings
title: Ujjwol Paudel | Homepage
author:
  name: Ujjwol Paudel
  email: upaudel1@asu.edu
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima

